-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Хост: localhost
-- Време на генериране: 29 яну 2024 в 21:44
-- Версия на сървъра: 10.4.28-MariaDB
-- Версия на PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данни: `web-conv`
--

--
-- Схема на данните от таблица `ProfileHistory`
--

INSERT INTO `ProfileHistory` (`username`, `inputField`, `configField`, `outputField`, `version`, `conversionType`, `comment`, `output`, `input`, `config`) VALUES
('helium', 1, 1, 2, '2024-01-25 19:07:17', 'properties2json', '', '{\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"in\": \"area1\",\n    \"out\": \"area2\"\n}', 'input_format = properties\r\noutput_format = json \r\nin = area1\r\nout = area2', 'input_format = properties\r\noutput_format = json \r\nin = area1\r\nout = area2'),
('helium', 2, 1, 3, '2024-01-25 19:11:06', 'json2properties', 'post exam test', 'quiz.sport.q1.question=Which one is correct team name in NBA?\nquiz.sport.q1.options.0=New York Bulls\nquiz.sport.q1.options.1=Los Angeles Kings\nquiz.sport.q1.options.2=Golden State Warriros\nquiz.sport.q1.options.3=Huston Rocket\nquiz.sport.q1.answer=Huston Rocket\nquiz.maths.q1.question=5 + 7 = ?\nquiz.maths.q1.options.0=10\nquiz.maths.q1.options.1=11\nquiz.maths.q1.options.2=12\nquiz.maths.q1.options.3=13\nquiz.maths.q1.answer=12\nquiz.maths.q2.question=12 - 8 = ?\nquiz.maths.q2.options.0=1\nquiz.maths.q2.options.1=2\nquiz.maths.q2.options.2=3\nquiz.maths.q2.options.3=4\nquiz.maths.q2.answer=4\n', '{\r\n    \"quiz\": {\r\n        \"sport\": {\r\n            \"q1\": {\r\n                \"question\": \"Which one is correct team name in NBA?\",\r\n                \"options\": [\r\n                    \"New York Bulls\",\r\n                    \"Los Angeles Kings\",\r\n                    \"Golden State Warriros\",\r\n                    \"Huston Rocket\"\r\n                ],\r\n                \"answer\": \"Huston Rocket\"\r\n            }\r\n        },\r\n        \"maths\": {\r\n            \"q1\": {\r\n                \"question\": \"5 + 7 = ?\",\r\n                \"options\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"answer\": \"12\"\r\n            },\r\n            \"q2\": {\r\n                \"question\": \"12 - 8 = ?\",\r\n                \"options\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"answer\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'input_format = json \r\noutput_format = properties\r\nin =area2\r\nout = area3'),
('helium', 1, 3, 2, '2024-01-25 19:38:40', 'properties2properties', 'ttest', 'input_format = properties\r\noutput_format = properties\r\nin = area1\r\nout = area2\r\nconfig = area3', 'input_format = properties\r\noutput_format = properties\r\nin = area1\r\nout = area2\r\nconfig = area3', 'input_format = properties\r\noutput_format = properties\r\nin = area1\r\nout = area2\r\nconfig = area3'),
('helium', 3, 1, 2, '2024-01-28 17:58:18', 'properties2json', 'temp', '{\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"in\": \"area3\",\n    \"out\": \"area2\",\n    \"config\": \"area1\"\n}', 'input_format = properties \r\noutput_format = json \r\nin = area3\r\nout = area2 \r\nconfig = area1', 'input_format = properties \r\noutput_format = json \r\nin = area3\r\nout = area2 \r\nconfig = area1'),
('helium', 2, 1, 3, '2024-01-28 19:37:37', 'json2properties', 'test out after modifications', 'quiz.sport.q1.question=Which one is correct team name in NBA?\nquiz.sport.q1.options.0=New York Bulls\nquiz.sport.q1.options.1=Los Angeles Kings\nquiz.sport.q1.options.2=Golden State Warriros\nquiz.sport.q1.options.3=Huston Rocket\nquiz.sport.q1.answer=Huston Rocket\nquiz.maths.q1.question=5 + 7 = ?\nquiz.maths.q1.options.0=10\nquiz.maths.q1.options.1=11\nquiz.maths.q1.options.2=12\nquiz.maths.q1.options.3=13\nquiz.maths.q1.answer=12\nquiz.maths.q2.question=12 - 8 = ?\nquiz.maths.q2.options.0=1\nquiz.maths.q2.options.1=2\nquiz.maths.q2.options.2=3\nquiz.maths.q2.options.3=4\nquiz.maths.q2.answer=4\n', '{\r\n    \"quiz\": {\r\n        \"sport\": {\r\n            \"q1\": {\r\n                \"question\": \"Which one is correct team name in NBA?\",\r\n                \"options\": [\r\n                    \"New York Bulls\",\r\n                    \"Los Angeles Kings\",\r\n                    \"Golden State Warriros\",\r\n                    \"Huston Rocket\"\r\n                ],\r\n                \"answer\": \"Huston Rocket\"\r\n            }\r\n        },\r\n        \"maths\": {\r\n            \"q1\": {\r\n                \"question\": \"5 + 7 = ?\",\r\n                \"options\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"answer\": \"12\"\r\n            },\r\n            \"q2\": {\r\n                \"question\": \"12 - 8 = ?\",\r\n                \"options\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"answer\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'input_format = json\r\noutput_format = properties\r\nin = area2\r\nout = area3'),
('helium', 2, 1, 2, '2024-01-28 19:44:38', 'json2properties', '', 'quiz.sport.q1.question=Which one is correct team name in NBA?\nquiz.sport.q1.options.0=New York Bulls\nquiz.sport.q1.options.1=Los Angeles Kings\nquiz.sport.q1.options.2=Golden State Warriros\nquiz.sport.q1.options.3=Huston Rocket\nquiz.sport.q1.answer=Huston Rocket\nquiz.maths.q1.question=5 + 7 = ?\nquiz.maths.q1.options.0=10\nquiz.maths.q1.options.1=11\nquiz.maths.q1.options.2=12\nquiz.maths.q1.options.3=13\nquiz.maths.q1.answer=12\nquiz.maths.q2.question=12 - 8 = ?\nquiz.maths.q2.options.0=1\nquiz.maths.q2.options.1=2\nquiz.maths.q2.options.2=3\nquiz.maths.q2.options.3=4\nquiz.maths.q2.answer=4\n', '{\r\n    \"quiz\": {\r\n        \"sport\": {\r\n            \"q1\": {\r\n                \"question\": \"Which one is correct team name in NBA?\",\r\n                \"options\": [\r\n                    \"New York Bulls\",\r\n                    \"Los Angeles Kings\",\r\n                    \"Golden State Warriros\",\r\n                    \"Huston Rocket\"\r\n                ],\r\n                \"answer\": \"Huston Rocket\"\r\n            }\r\n        },\r\n        \"maths\": {\r\n            \"q1\": {\r\n                \"question\": \"5 + 7 = ?\",\r\n                \"options\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"answer\": \"12\"\r\n            },\r\n            \"q2\": {\r\n                \"question\": \"12 - 8 = ?\",\r\n                \"options\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"answer\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'input_format = json\r\noutput_format = properties\r\nin = area2\r\nout = area2'),
('helium', 1, 1, 2, '2024-01-29 19:01:41', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": {\n                \"all\": \"in\"\n            }\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json'),
('helium', 1, 1, 2, '2024-01-29 19:12:34', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": {\n                \"all\": \"in\"\n            }\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json'),
('helium', 1, 1, 2, '2024-01-29 19:13:22', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": {\n                \"all\": \"in\"\n            }\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json'),
('helium', 1, 1, 2, '2024-01-29 19:13:46', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": {\n                \"all\": \"in\"\n            }\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json'),
('helium', 1, 1, 2, '2024-01-29 19:14:15', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": {\n                \"all\": \"in\"\n            }\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json'),
('helium', 1, 1, 2, '2024-01-29 20:18:45', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": {\n                \"all\": \"in\"\n            }\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json'),
('helium', 1, 1, 2, '2024-01-29 20:19:52', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\"\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"tranform\": [\n        {\n            \"key\": \"in\"\n        }\n    ]\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntranform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntranform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 20:21:10', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 20:25:19', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 20:28:23', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 20:39:56', 'properties2properties', '', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 20:40:46', 'properties2properties', '', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 20:43:19', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 20:44:03', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"in\": \"area1\",\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:05:19', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:05:42', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:06:06', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:06:52', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:07:17', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:07:51', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:08:26', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:08:51', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:09:29', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"\\u0438\\u043d\": \"\\u0430\\u0440\\u0435\\u04301\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:12:48', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area2\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"ин\": \"ареа1\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 1, 1, 2, '2024-01-29 21:14:30', 'properties2json', '', '{\n    \"трансформ\": [\n        {\n            \"тйпе\": \"то_цйриллицс\",\n            \"алл\": \"труе\"\n        }\n    ],\n    \"ин\": \"ареа1\",\n    \"оут\": \"ареа2\",\n    \"инпут_формат\": \"пропертиес\",\n    \"оутпут_формат\": \"йсон\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'transform.0.type.all = in\r\nin = area1\r\nout = area2\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 1, 1, 3, '2024-01-29 21:16:15', 'properties2json', '', '{\n    \"transform\": [\n        {\n            \"type\": \"to_cyrillics\",\n            \"key\": \"in\"\n        }\n    ],\n    \"out\": \"area3\",\n    \"input_format\": \"properties\",\n    \"output_format\": \"json\",\n    \"ин\": \"ареа1\"\n}', 'transform.0.type.all = in\r\nin = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in', 'transform.0.type.all = in\r\nin = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = json\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = in'),
('helium', 2, 1, 3, '2024-01-29 21:20:53', 'json2properties', '', 'яуиз.спорт.я1.яуестион=Вхич оне ис цоррецт теам наме ин НБА?\nяуиз.спорт.я1.оптионс.0=Нев Йорк Буллс\nяуиз.спорт.я1.оптионс.1=Лос Ангелес Кингс\nяуиз.спорт.я1.оптионс.2=Голден Стате Варрирос\nяуиз.спорт.я1.оптионс.3=Хустон Роцкет\nяуиз.спорт.я1.ансвер=Хустон Роцкет\nяуиз.матхс.я1.яуестион=5 + 7 = ?\nяуиз.матхс.я1.оптионс.0=10\nяуиз.матхс.я1.оптионс.1=11\nяуиз.матхс.я1.оптионс.2=12\nяуиз.матхс.я1.оптионс.3=13\nяуиз.матхс.я1.ансвер=12\nяуиз.матхс.я2.яуестион=12 - 8 = ?\nяуиз.матхс.я2.оптионс.0=1\nяуиз.матхс.я2.оптионс.1=2\nяуиз.матхс.я2.оптионс.2=3\nяуиз.матхс.я2.оптионс.3=4\nяуиз.матхс.я2.ансвер=4\n', '{\r\n    \"quiz\": {\r\n        \"sport\": {\r\n            \"q1\": {\r\n                \"question\": \"Which one is correct team name in NBA?\",\r\n                \"options\": [\r\n                    \"New York Bulls\",\r\n                    \"Los Angeles Kings\",\r\n                    \"Golden State Warriros\",\r\n                    \"Huston Rocket\"\r\n                ],\r\n                \"answer\": \"Huston Rocket\"\r\n            }\r\n        },\r\n        \"maths\": {\r\n            \"q1\": {\r\n                \"question\": \"5 + 7 = ?\",\r\n                \"options\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"answer\": \"12\"\r\n            },\r\n            \"q2\": {\r\n                \"question\": \"12 - 8 = ?\",\r\n                \"options\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"answer\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'transform.0.type.all = in\r\nin = area2\r\nout = area3\r\ninput_format = json\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 1, 1, 3, '2024-01-29 21:22:17', 'properties2properties', '', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\n'),
('helium', 1, 1, 3, '2024-01-29 21:23:25', 'properties2properties', '', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 1, 1, 3, '2024-01-29 21:23:53', 'properties2properties', '', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 1, 1, 3, '2024-01-29 21:24:27', 'properties2properties', '', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 1, 1, 3, '2024-01-29 21:26:30', 'properties2properties', '', 'ин=ареа1\nоут=ареа3\nинпут_формат=пропертиес\nоутпут_формат=пропертиес\nтрансформ.0.тйпе=то_цйриллицс\nтрансформ.0.алл=труе\n', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true', 'in = area1\r\nout = area3\r\ninput_format = properties\r\noutput_format = properties\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 2, 1, 3, '2024-01-29 21:28:28', 'json2json', '', '{\n    \"яуиз\": {\n        \"спорт\": {\n            \"я1\": {\n                \"яуестион\": \"Вхич оне ис цоррецт теам наме ин НБА?\",\n                \"оптионс\": [\n                    \"Нев Йорк Буллс\",\n                    \"Лос Ангелес Кингс\",\n                    \"Голден Стате Варрирос\",\n                    \"Хустон Роцкет\"\n                ],\n                \"ансвер\": \"Хустон Роцкет\"\n            }\n        },\n        \"матхс\": {\n            \"я1\": {\n                \"яуестион\": \"5 + 7 = ?\",\n                \"оптионс\": [\n                    \"10\",\n                    \"11\",\n                    \"12\",\n                    \"13\"\n                ],\n                \"ансвер\": \"12\"\n            },\n            \"я2\": {\n                \"яуестион\": \"12 - 8 = ?\",\n                \"оптионс\": [\n                    \"1\",\n                    \"2\",\n                    \"3\",\n                    \"4\"\n                ],\n                \"ансвер\": \"4\"\n            }\n        }\n    }\n}', '{\r\n    \"quiz\": {\r\n        \"sport\": {\r\n            \"q1\": {\r\n                \"question\": \"Which one is correct team name in NBA?\",\r\n                \"options\": [\r\n                    \"New York Bulls\",\r\n                    \"Los Angeles Kings\",\r\n                    \"Golden State Warriros\",\r\n                    \"Huston Rocket\"\r\n                ],\r\n                \"answer\": \"Huston Rocket\"\r\n            }\r\n        },\r\n        \"maths\": {\r\n            \"q1\": {\r\n                \"question\": \"5 + 7 = ?\",\r\n                \"options\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"answer\": \"12\"\r\n            },\r\n            \"q2\": {\r\n                \"question\": \"12 - 8 = ?\",\r\n                \"options\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"answer\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'input_format = json \r\noutput_format = json\r\nin = area2\r\nout = area3\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 2, 1, 3, '2024-01-29 21:32:35', 'json2properties', '', 'яуиз.спорт.я1.яуестион=Вхич оне ис цоррецт теам наме ин НБА?\nяуиз.спорт.я1.оптионс.0=Нев Йорк Буллс\nяуиз.спорт.я1.оптионс.1=Лос Ангелес Кингс\nяуиз.спорт.я1.оптионс.2=Голден Стате Варрирос\nяуиз.спорт.я1.оптионс.3=Хустон Роцкет\nяуиз.спорт.я1.ансвер=Хустон Роцкет\nяуиз.матхс.я1.яуестион=5 + 7 = ?\nяуиз.матхс.я1.оптионс.0=10\nяуиз.матхс.я1.оптионс.1=11\nяуиз.матхс.я1.оптионс.2=12\nяуиз.матхс.я1.оптионс.3=13\nяуиз.матхс.я1.ансвер=12\nяуиз.матхс.я2.яуестион=12 - 8 = ?\nяуиз.матхс.я2.оптионс.0=1\nяуиз.матхс.я2.оптионс.1=2\nяуиз.матхс.я2.оптионс.2=3\nяуиз.матхс.я2.оптионс.3=4\nяуиз.матхс.я2.ансвер=4\n', '{\r\n    \"quiz\": {\r\n        \"sport\": {\r\n            \"q1\": {\r\n                \"question\": \"Which one is correct team name in NBA?\",\r\n                \"options\": [\r\n                    \"New York Bulls\",\r\n                    \"Los Angeles Kings\",\r\n                    \"Golden State Warriros\",\r\n                    \"Huston Rocket\"\r\n                ],\r\n                \"answer\": \"Huston Rocket\"\r\n            }\r\n        },\r\n        \"maths\": {\r\n            \"q1\": {\r\n                \"question\": \"5 + 7 = ?\",\r\n                \"options\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"answer\": \"12\"\r\n            },\r\n            \"q2\": {\r\n                \"question\": \"12 - 8 = ?\",\r\n                \"options\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"answer\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'input_format = json \r\noutput_format = properties\r\nin = area2\r\nout = area3\r\ntransform.0.type = to_cyrillics\r\ntransform.0.all = true'),
('helium', 1, 2, 3, '2024-01-29 21:42:35', 'properties2properties', '', 'input_format=пропертиес\noutput_format=properties\nin=area1\nconfig=area2\nout=area3\ntransform.0.type=to_cyrillics\ntransform.0.key=input_format\ntransform.0.value_apply=true\n', 'input_format = properties \r\noutput_format = properties\r\nin = area1\r\nconfig = area2\r\nout = area3\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = input_format\r\ntransform.0.value_apply = true', 'input_format = properties \r\noutput_format = properties\r\nin = area1\r\nconfig = area2\r\nout = area3\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = input_format\r\ntransform.0.value_apply = true'),
('helium', 2, 2, 3, '2024-01-29 21:44:05', 'properties2properties', '', 'input_format=пропертиес\noutput_format=properties\nin=area2\nout=area3\ntransform.0.type=to_cyrillics\ntransform.0.key=input_format\ntransform.0.value_apply=true\n', 'input_format = properties \r\noutput_format = properties\r\nin = area2\r\nout = area3\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = input_format\r\ntransform.0.value_apply = true', 'input_format = properties \r\noutput_format = properties\r\nin = area2\r\nout = area3\r\ntransform.0.type = to_cyrillics\r\ntransform.0.key = input_format\r\ntransform.0.value_apply = true'),
('helium', 3, 2, 3, '2024-01-29 21:45:07', 'properties2properties', '', 'input_format=пропертиес\noutput_format=PROPERTIES\nin=area2\nout=area3\ntransform.0.type=to_cyrillics\ntransform.0.key=input_format\ntransform.0.value_apply=true\n', 'input_format=пропертиес\r\noutput_format=properties\r\nin=area2\r\nout=area3\r\ntransform.0.type=to_cyrillics\r\ntransform.0.key=input_format\r\ntransform.0.value_apply=true', 'input_format = properties \r\noutput_format = properties\r\nin = area3\r\nout = area3\r\ntransform.0.type = to_uppercase\r\ntransform.0.key = output_format\r\ntransform.0.value_apply = true'),
('helium', 2, 2, 3, '2024-01-29 21:47:38', 'properties2properties', '', 'INPUT_FORMAT=PROPERTIES\nOUTPUT_FORMAT=PROPERTIES\nIN=AREA2\nOUT=AREA3\nTRANSFORM.0.TYPE=TO_UPPERCASE\nTRANSFORM.0.ALL=TRUE\n', 'input_format = properties \r\noutput_format = properties\r\nin = area2\r\nout = area3\r\ntransform.0.type = to_uppercase\r\ntransform.0.all = true', 'input_format = properties \r\noutput_format = properties\r\nin = area2\r\nout = area3\r\ntransform.0.type = to_uppercase\r\ntransform.0.all = true'),
('helium', 1, 2, 3, '2024-01-29 22:12:00', 'json2properties', 'към шльокавица, json2properties DEMO', 'quiz.sport.q1.question=Vhi4 one is tsorretst team name in NBA?\nquiz.sport.q1.options.0=Nev York Bulls\nquiz.sport.q1.options.1=Los Angeles Kings\nquiz.sport.q1.options.2=Golden State Varriros\nquiz.sport.q1.options.3=Huston Rotsket\nquiz.sport.q1.ansver=Huston Rotsket\nquiz.maths.q1.question=5 + 7 = ?\nquiz.maths.q1.options.0=10\nquiz.maths.q1.options.1=11\nquiz.maths.q1.options.2=12\nquiz.maths.q1.options.3=13\nquiz.maths.q1.ansver=12\nquiz.maths.q2.question=12 - 8 = ?\nquiz.maths.q2.options.0=1\nquiz.maths.q2.options.1=2\nquiz.maths.q2.options.2=3\nquiz.maths.q2.options.3=4\nquiz.maths.q2.ansver=4\n', '{\r\n    \"яуиз\": {\r\n        \"спорт\": {\r\n            \"я1\": {\r\n                \"яуестион\": \"Вхич оне ис цоррецт теам наме ин НБА?\",\r\n                \"оптионс\": [\r\n                    \"Нев Йорк Буллс\",\r\n                    \"Лос Ангелес Кингс\",\r\n                    \"Голден Стате Варрирос\",\r\n                    \"Хустон Роцкет\"\r\n                ],\r\n                \"ансвер\": \"Хустон Роцкет\"\r\n            }\r\n        },\r\n        \"матхс\": {\r\n            \"я1\": {\r\n                \"яуестион\": \"5 + 7 = ?\",\r\n                \"оптионс\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"ансвер\": \"12\"\r\n            },\r\n            \"я2\": {\r\n                \"яуестион\": \"12 - 8 = ?\",\r\n                \"оптионс\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"ансвер\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'input_format = json \r\noutput_format = properties\r\nin = area1\r\nout = area3\r\ntransform.1.type = to_shlyokavica\r\ntransform.1.all = true'),
('sherlocked', 1, 3, 2, '2024-01-25 19:21:34', 'properties2json', 'tttest', '{\n    \"quiz\": {\n        \"sport\": {\n            \"q1\": {\n                \"question\": \"Which one is correct team name in NBA?\",\n                \"options\": [\n                    \"New York Bulls\",\n                    \"Los Angeles Kings\",\n                    \"Golden State Warriros\",\n                    \"Huston Rocket\"\n                ],\n                \"answer\": \"Huston Rocket\"\n            }\n        },\n        \"maths\": {\n            \"q1\": {\n                \"question\": \"5 + 7 = ?\",\n                \"options\": [\n                    \"10\",\n                    \"11\",\n                    \"12\",\n                    \"13\"\n                ],\n                \"answer\": \"12\"\n            },\n            \"q2\": {\n                \"question\": \"12 - 8 = ?\",\n                \"options\": [\n                    \"1\",\n                    \"2\",\n                    \"3\",\n                    \"4\"\n                ],\n                \"answer\": \"4\"\n            }\n        }\n    }\n}', 'quiz.sport.q1.question=Which one is correct team name in NBA?\r\nquiz.sport.q1.options.0=New York Bulls\r\nquiz.sport.q1.options.1=Los Angeles Kings\r\nquiz.sport.q1.options.2=Golden State Warriros\r\nquiz.sport.q1.options.3=Huston Rocket\r\nquiz.sport.q1.answer=Huston Rocket\r\nquiz.maths.q1.question=5 + 7 = ?\r\nquiz.maths.q1.options.0=10\r\nquiz.maths.q1.options.1=11\r\nquiz.maths.q1.options.2=12\r\nquiz.maths.q1.options.3=13\r\nquiz.maths.q1.answer=12\r\nquiz.maths.q2.question=12 - 8 = ?\r\nquiz.maths.q2.options.0=1\r\nquiz.maths.q2.options.1=2\r\nquiz.maths.q2.options.2=3\r\nquiz.maths.q2.options.3=4\r\nquiz.maths.q2.answer=4', ''),
('sherlocked', 2, 2, 2, '2024-01-25 19:36:32', 'json2properties', 'better?', 'quiz.sport.q1.question=Which one is correct team name in NBA?\nquiz.sport.q1.options.0=New York Bulls\nquiz.sport.q1.options.1=Los Angeles Kings\nquiz.sport.q1.options.2=Golden State Warriros\nquiz.sport.q1.options.3=Huston Rocket\nquiz.sport.q1.answer=Huston Rocket\nquiz.maths.q1.question=5 + 7 = ?\nquiz.maths.q1.options.0=10\nquiz.maths.q1.options.1=11\nquiz.maths.q1.options.2=12\nquiz.maths.q1.options.3=13\nquiz.maths.q1.answer=12\nquiz.maths.q2.question=12 - 8 = ?\nquiz.maths.q2.options.0=1\nquiz.maths.q2.options.1=2\nquiz.maths.q2.options.2=3\nquiz.maths.q2.options.3=4\nquiz.maths.q2.answer=4\n', '{\r\n    \"quiz\": {\r\n        \"sport\": {\r\n            \"q1\": {\r\n                \"question\": \"Which one is correct team name in NBA?\",\r\n                \"options\": [\r\n                    \"New York Bulls\",\r\n                    \"Los Angeles Kings\",\r\n                    \"Golden State Warriros\",\r\n                    \"Huston Rocket\"\r\n                ],\r\n                \"answer\": \"Huston Rocket\"\r\n            }\r\n        },\r\n        \"maths\": {\r\n            \"q1\": {\r\n                \"question\": \"5 + 7 = ?\",\r\n                \"options\": [\r\n                    \"10\",\r\n                    \"11\",\r\n                    \"12\",\r\n                    \"13\"\r\n                ],\r\n                \"answer\": \"12\"\r\n            },\r\n            \"q2\": {\r\n                \"question\": \"12 - 8 = ?\",\r\n                \"options\": [\r\n                    \"1\",\r\n                    \"2\",\r\n                    \"3\",\r\n                    \"4\"\r\n                ],\r\n                \"answer\": \"4\"\r\n            }\r\n        }\r\n    }\r\n}', 'input_format = json \r\noutput_format = properties\r\nin = area2\r\nout = area2\r\nconfig = area2');

--
-- Схема на данните от таблица `users`
--

INSERT INTO `users` (`username`, `name`, `passwd`, `email`) VALUES
('helium', 'Diana Markova', '$2y$10$400TfckwCivMnSP/q1qCPuWbMQRGl1/EmJsuywapDbxk8BSkEA8ce', 'dventsisla@uni-sofia.bg'),
('pesho42', 'Pesho', '$2y$10$M.UtL.q5iG.QXpE2E/rx9eqV3oZOTAEHCzD32xaEFYVjCP9Sv5ENe', 'pesho@gosho.com'),
('sherlocked', 'Sherlock Holmes', '$2y$10$fJTKyRRLOrSG6x4qXdq3Te8K0uKoOv0a6rdBte6Yq/8SGv9ew5d7i', 'sherlock@221b.bakerstreet');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
